In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import random
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer #文本处理工具
from sklearn.naive_bayes import MultinomialNB #多项式
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

e:\anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
data = pd.read_csv("./web_input.csv")
data

tag                                              value
0       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
1       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
2       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
3       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
4       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
5       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
6       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
7       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
8       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
9       SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
10      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
11      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
12      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
13      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
14      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
15      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
16      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
17      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
18      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
19      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
20      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
21      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
22      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
23      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
24      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
25      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
26      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
27      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
28      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
29      SQL注入攻击  /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
...         ...                                                ...
145477   normal                                       /~kmane/\r\n
145478   normal                        /javascript/surveys.pfx\r\n
145479   normal                         /predatorylendingmenu/\r\n
145480   normal                                    /615956790/\r\n
145481   normal                                      /mnumain/\r\n
145482   normal                                       /boiler/\r\n
145483   normal                                  /phil_jensen/\r\n
145484   normal                                /1165080920206/\r\n
145485   normal  /dialogs/td.php?spaw_dir=http://192.168.202.11...
145486   normal                          /javascript/crack.jpg\r\n
145487   normal                                  /topicbrowse/\r\n
145488   normal                                      /3419580/\r\n
145489   normal                              /hockey_software/\r\n
145490   normal                                      /n300967/\r\n
145491   normal                                   /20050808-9/\r\n
145492   normal                             /javascript/01.rss\r\n
145493   normal                          /procmail_mindspring/\r\n
145494   normal                                /counter_image/\r\n
145495   normal                            /chinese valentine/\r\n
145496   normal                                 /churchspeaks/\r\n
145497   normal                                    /000026199/\r\n
145498   normal                /mastering windows xp registry/\r\n
145499   normal                                      /6216848/\r\n
145500   normal                                    /euro-sepg/\r\n
145501   normal                                    /p0008798b/\r\n
145502   normal                                    /thepaintr/\r\n
145503   normal                                 /javascript/ie\r\n
145504   normal                                     /165263

In [3]:
data.shape

(145507, 2)

In [4]:
x = data["value"] #表示取第一列
x

0         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
1         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
2         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
3         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
4         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
5         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
6         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
7         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
8         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
9         /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
10        /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
11        /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
12        /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
13        /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
14        /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
15        /savehf.asp HTTP/1.1\r\r\nAccept: text/xml,app...
16        /savehf.asp HTTP/1.1\r\r\nAcce

In [5]:
tf = TfidfVectorizer() #文本矢量处理
x = tf.fit_transform(x)
x.shape

(145507, 119841)

In [6]:
y = data["tag"]
mydict = {'SQL注入攻击':1, 'XSS跨站脚本':2, 'normal':3}
# 得到训练和测试数据集
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.80)
y_train = y_train.map(mydict) #把非字符型数据映射为字符型数据
y_test = y_test.map(mydict)

e:\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [7]:
mnb = MultinomialNB()
mnb.fit(x_train, y_train)
print("   ",mnb.score(x_test, y_test))
p_data = mnb.predict(x_test[:20]) #预测
print("   ",p_data)

    0.997697752731771
    [2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [8]:
# 多项式朴素贝叶斯算法，Multinomial Naive Bayes，函数名，multinomialnb
def mx_bayes(train_x, train_y):
    mx = MultinomialNB(alpha=0.01)
    mx.fit(train_x, train_y.astype('int'))
    return mx

# 随机随机森林算法,random forest classifier，函数名,RandomForestClassifier
def mx_forest(train_x, train_y):
    mx = RandomForestClassifier(n_estimators=8)
    mx.fit(train_x, train_y)
    return mx

# SVM向量机算法，函数名 SVC
def mx_svm(train_x, train_y):
    mx = SVC(kernel='rbf', probability=True)
    mx.fit(train_x, train_y)
    return mx

# MLP神经网络算法
def mx_MLP(train_x, train_y):
    mx = MLPClassifier()
    mx.fit(train_x, train_y)
    return mx

mxfunSgn = {'bayes': mx_bayes,
            'forest': mx_forest,
            'svm': mx_svm,
            'mlp': mx_MLP,
            }

resultlist = {}
for k in mxfunSgn:
    try:
        mx = mxfunSgn[k](x_train, y_train)
        score = mx.score(x_test, y_test)
        pre_result = mx.predict(x_test)
        print("     ",pre_result[:20])
        print("     ",y_test[:20].tolist())
        print("     ",k, score)
        resultlist[k] = score
    except:
        score = 0
        
print("....max  :", sorted(resultlist, key=lambda x:resultlist[x])[-1:],
      resultlist[sorted(resultlist, key=lambda x:resultlist[x])[-1]])
print("....nextmax  :", sorted(resultlist, key=lambda x:resultlist[x])[-2],
      resultlist[sorted(resultlist, key=lambda x:resultlist[x])[-2]])
print("....thirdmax  :", sorted(resultlist, key=lambda x:resultlist[x])[-3],
      resultlist[sorted(resultlist, key=lambda x:resultlist[x])[-3]])

      [2 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3]
      [2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
      bayes 0.9952924197649646
      [2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
      [2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
      forest 0.9989347811147
      [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
      [2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
      svm 0.9336128101161432
      [2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
      [2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
      mlp 0.9994158477080614
....max  : ['mlp'] 0.9994158477080614
....nextmax  : forest 0.9989347811147
....thirdmax  : bayes 0.9952924197649646
